steps:
  - name: node
    entrypoint: npm
    args: ["install"]

  - name: node
    entrypoint: npm
    args: ["run", "build"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["-m", "rm", "gs://staging.assetalchemy.io/**"]

  - name: "gcr.io/cloud-builders/gsutil"
    dir: "public"
    args: ["-m", "cp", "-r", ".", "gs://staging.assetalchemy.io/"]
